services:
  details:
    build: ./details
    image: ghcr.io/supakit25433/bookinfo-details:dev
    ports:
      - "8081:8081"
    environment:
      ENABLE_EXTERNAL_BOOK_SERVICE: "true"
      DO_NOT_ENCRYPT: "false"
  productpage:
    build: ./productpage
    image: ghcr.io/supakit25433/productpage:dev
    ports:
      - "8083:8083"
    environment:
      DETAILS_HOSTNAME: "http://details:8081"
      RATINGS_HOSTNAME: "http://ratings:8080"
      REVIEWS_HOSTNAME: "http://reviews:8082"
      FLOOD_FACTOR: 0
  ratings:
    build: ./ratings
    image: ghcr.io/supakit25433/bookinfo-ratings:dev
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://mongodb:27017/ratings
      MONGO_DB_USERNAME: ratings
      MONGO_DB_PASSWORD: CHANGEME
  mongodb:
    image: bitnami/mongodb:5.0.2-debian-10-r2
    volumes:
      - "./ratings/databases:/docker-entrypoint-initdb.d"
    environment:
      MONGODB_ROOT_PASSWORD: CHANGEME
      MONGODB_USERNAME: ratings
      MONGODB_PASSWORD: CHANGEME
      MONGODB_DATABASE: ratings
  reviews:
    build: ./reviews
    image: ghcr.io/supakit25433/bookinfo-reviews:dev
    ports:
      - "8082:8082"
    environment:
      ENABLE_RATINGS: "true"
      RATINGS_SERVICE: "http://ratings:8080"